# Generated by Django 4.2.20 on 2025-03-14 02:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default='PRF-4ee4b368', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('SUPER-ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('USER', 'User'), ('GUEST', 'Guest')], default='USER', max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default='USR-fe09420d', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=101)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('username', models.CharField(max_length=50, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', to='authentication.user')),
                ('profileName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.profile')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default='SES-5c90a508', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('action', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sessions', to='authentication.user')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='createdById',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastModifiedById',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_profiles', to='authentication.user'),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.CharField(default='LGN-ac3de12c', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('token1', models.CharField(max_length=255)),
                ('token2', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_logins', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_logins', to='authentication.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='authentication.user')),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
