# Generated by Django 4.2.20 on 2025-03-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.CharField(default='RTY-6fb30180', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_record_types', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_record_types', to='authentication.user')),
            ],
            options={
                'db_table': 'RecordType',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default='ADR-41669789', max_length=20, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_addresses', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_addresses', to='authentication.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='authentication.user')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
