# Generated by Django 4.2.20 on 2025-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.CharField(default='ADR-598f6dcd', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='id',
            field=models.CharField(default='RTY-95b448e8', max_length=20, primary_key=True, serialize=False),
        ),
    ]
