# Generated by Django 4.2.20 on 2025-03-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default='NTF-89db4d55', max_length=20, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('isRead', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_notifications', to='authentication.user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.user')),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
    ]
