# Generated by Django 4.2.20 on 2025-03-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.CharField(default='CRT-825a821c', max_length=20, primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_carts', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_carts', to='authentication.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='authentication.user')),
            ],
            options={
                'db_table': 'ShoppingCart',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(default='CAS-9cb8c4bc', max_length=20, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='New', max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='authentication.user')),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cases', to='authentication.user')),
            ],
            options={
                'db_table': 'Case',
            },
        ),
    ]
