# Generated by Django 4.2.20 on 2025-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.CharField(default='CAS-378ddca0', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='id',
            field=models.CharField(default='CRT-186d255d', max_length=20, primary_key=True, serialize=False),
        ),
    ]
