# Generated by Django 4.2.20 on 2025-03-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='PRD-22fea4c5', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_products', to='authentication.user')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.CharField(default='ITM-c1f9411c', max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_items', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_product_items', to='authentication.user')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product')),
                ('shoppingCartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.shoppingcart')),
            ],
            options={
                'db_table': 'ProductItem',
            },
        ),
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.CharField(default='PRC-7cdd3b32', max_length=20, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_books', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_price_books', to='authentication.user')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_books', to='products.product')),
            ],
            options={
                'db_table': 'PriceBook',
            },
        ),
    ]
