# Generated by Django 4.2.20 on 2025-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebook',
            name='id',
            field=models.CharField(default='PRC-654882f4', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='PRD-377f6507', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='id',
            field=models.CharField(default='ITM-66764ba0', max_length=20, primary_key=True, serialize=False),
        ),
    ]
