# Generated by Django 4.2.20 on 2025-03-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.CharField(default='CRD-533e0e6a', max_length=20, primary_key=True, serialize=False)),
                ('cardNumber', models.CharField(max_length=255)),
                ('expiryDate', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=255)),
                ('cardHolderName', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_cards', to='authentication.user')),
                ('lastModifiedById', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_bank_cards', to='authentication.user')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to='authentication.user')),
            ],
            options={
                'db_table': 'BankCard',
            },
        ),
    ]
