# Generated by Django 4.2.20 on 2025-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='id',
            field=models.CharField(default='CRD-7f84d85b', max_length=20, primary_key=True, serialize=False),
        ),
    ]
